### ISSUE TITLE
Android unable to build sample

### ISSUE THREAD

**Issue by NVentimiglia** [dkornev/TwilioXamarinBindings#10]
1. Downloaded sample
2. Sample was missing the sln file, generated it
3. Preformed nuget restore
4. Unable to build project, having issues with the resource layout file
5. I googled the issue, and found a number of people having it on the xamarin forms. I attempted some of the things they suggested such as renaming the file, upgrading my sdks, ect. Nothing seemed to work.

![image](https://user-images.githubusercontent.com/125889/62429004-b7309780-b6bd-11e9-9ccc-fb4a2596f681.png)

**Comment by NVentimiglia** [comment]
![image](https://user-images.githubusercontent.com/125889/62429021-037bd780-b6be-11e9-883b-2fce5953b98c.png)

**Comment by dkornev** [comment]
I have updated Twilio Video Android binding to 4.3.0 and tested it.
But now it's moved to a separate repository: https://github.com/dkornev/TwilioVideoXamarinAndroid
