### ISSUE TITLE
Update twilio video-android binding to v3.x.x

### ISSUE THREAD

**Issue by ksavidetove** [dkornev/TwilioXamarinBindings#2]
First of all, thank you for your amazing contribution with this Xamarin binding of Twilio.

I'm trying to do the same thing with the version 3 of twilio video for android, knowing that this version is fixing latest compatibilitiy issues due to Firefox last breaking changes.

But I'm stuck in a situation where, trying to build the binding project with the latest twilio-video.aar (build action set to LibraryProjectZip), I get error messages about the WebRTC dependency.

![image](https://user-images.githubusercontent.com/18190507/52500283-e61df300-2bdd-11e9-86ca-99a7b8cbf7aa.png)

**Comment by dkornev** [comment]
Hi @ksavidetove , thank you, glad to help!
Native library binding is a kind of advanced topic, so I recommend you to read https://developer.xamarin.com/guides/android/advanced_topics/binding-a-java-library/customizing-bindings/java-bindings-metadata/ first.
In your case it looks like binding tool is generating a method proxy with the wrong name (which is already taken by another generated method). I had this problem before when I was working on 2.* binding, take a look at https://github.com/dkornev/TwilioXamarinBindings/blob/master/source/Twilio.Video.Android/v2/Transforms/Metadata.xml where I set specific _managedName_ for the same reason.

BTW, I'm planning to update Twilio Video Android SDK to 3.* the next one. But no dates yet.

**Comment by dkornev** [comment]
@ksavidetove Thank you so much for your contributing. I'll try to instal VS 2019 and review the PV on the weekend

**Comment by ksavidetove** [comment]
@dkornev Hi! Could you review and merge the PR please?

**Comment by ksavidetove** [comment]
Thanks for the PR.

Unfortunatly I can't find the last version of this binding using Nuget, the latest available version is 2.6.

And I think you should warn the users that VS 2019 is mandatory to make it work, it could spare some debug time.

**Comment by dkornev** [comment]
I could build the project on VS 2019 (Preview) for Mac without adding <AndroidDexTool>d8</AndroidDexTool>. I'll add using VS 2019 as a recommendation, but I'm not sure that it's necessary.
