### ISSUE TITLE
TVIRemoteParticipantDelegate events not firing on iOS

### ISSUE THREAD

**Issue by alexkivikoski** [dkornev/TwilioXamarinBindings#4]
Thank you for your work on this library, it has made it possible for us to integrate Twilio Video to our application!

After updating to the latest package and Twilio Video 2.x, our iOS app is no longer displaying remote video. It seems that the reason is that none of the events in TVIRemoteParticipantDelegate are firing. The Android library works fine.

Other events (in TVIRoomDelegate at least) seem to work as intented. I am using them as suggested in the sample code (by using the static instances of TwilioRoomDelegate, RemoteParticipantDelegate etc).

I have tried building the bindings projects myself and that did not resolve the issue.

Can you help us find a solution to this problem?

**Comment by InnovativeTechies** [comment]
@alexkivikoski kindly post how you are using TVIRemoteParticipantDelegate in your application. There are some methods got changed and u need to modify accordingly

**Comment by alexkivikoski** [comment]
I tried using the static instance:


```
RemoteParticipantDelegate participantDelegate => RemoteParticipantDelegate.Instance;  

//...

participantDelegate.SubscribedToVideoTrackEvent += (object sender, (TVIRemoteVideoTrack videoTrack, TVIRemoteVideoTrackPublication publication, TVIRemoteParticipant participant) e) => 
{
//not firing
};
```


Then implementing the interface:
```
public partial class VideoCallView : MyMvxViewController<VideoCallViewModel>, ITVIRemoteParticipantDelegate  
{
// ...
[Export("subscribedToVideoTrack:publication:forParticipant:")]
        public void SubscribedToVideoTrack(TVIRemoteVideoTrack videoTrack, TVIRemoteVideoTrackPublication publication, TVIRemoteParticipant participant)
        {
            // not firing
        }
}
```

I also checked and the TVIRemoteParticipant.Delegate property is null when RoomParticipantDidConnectEvent is fired.

```
roomDelegate.RoomParticipantDidConnectEvent += (object sender, (TVIRoom room, TVIRemoteParticipant participant) e) => 
{
//e.participant.Delegate is null
}
```

**Comment by dkornev** [comment]
@alexkivikoski you should set the instance as a participant delegate in two places (please see original 
 quickstart tutorial https://github.com/twilio/video-quickstart-swift/tree/master/VideoQuickStart):
`      private void RoomDelegateOnDidConnectToRoomEvent(object sender, TVIRoom e)
        {
            LogHelper.Info($"Connected to room {e?.Name} as {e?.LocalParticipant?.Identity}");
            if (e?.RemoteParticipants?.Length > 0)
            {
                RemoteParticipant = e.RemoteParticipants[0];
                if (RemoteParticipant != null)
                {
                    RemoteParticipant.Delegate = RemoteParticipantDelegate.Instance;
                }
            }
        }

        private void RoomDelegateOnRoomParticipantDidConnectEvent(object sender, (TVIRoom room, TVIRemoteParticipant participant) e)
        {
            if (RemoteParticipant == null)
            {
                RemoteParticipant = e.participant;
                if (RemoteParticipant != null)
                {
                    RemoteParticipant.Delegate = RemoteParticipantDelegate.Instance;
                }
            }
            LogHelper.Info($"Participant {e.participant?.Identity} connected with {e.participant?.RemoteAudioTracks?.Length} audio and {e.participant?.RemoteVideoTracks?.Length} video tracks");
        }
`
And these are events of RoomDelegate, you set it when you connect to a room:
`   public TVIRoom ConnectToRoom(string token, TVILocalAudioTrack localAudioTrack, TVILocalVideoTrack localVideoTrack, string roomName)
        {
            LogHelper.Call(nameof(RoomDelegate), nameof(ConnectToRoom));
            InProgress = true;

            var connectOptions = TVIConnectOptions.OptionsWithToken(token, builder =>
            {
                builder.AudioTracks = new[] { localAudioTrack };
                builder.VideoTracks = new[] { localVideoTrack };
                builder.RoomName = roomName;
            });

            return TwilioVideo.ConnectWithOptions(connectOptions, Instance);
        }`

Does that help?

**Comment by dkornev** [comment]
@alexkivikoski Also, thanks for your feedback. But I'm using this binding for some apps in AppStore without any issues

**Comment by alexkivikoski** [comment]
@dkornev Thank you for quick reply and help. I did try to follow the QuickStart example but I must have missed that. The binding does work perfectly, you can close this issue now.
