### ISSUE TITLE
Linker Command failed with exit code 1

### ISSUE THREAD

**Issue by kier70** [dkornev/TwilioXamarinBindings#5]
Thanks for the help with the bindings, I'm not sure why Twilio isn't implementing these features already but thanks for filling the gap.

My problem is, I have a pretty non standard setup (I think) in that I've had to put your voice bindings in a separate solution then reference the dll - something that came about with the fact that the NuGet package wouldn't expose the namespace. 

The resultant dll is 146MB so I'm presuming it all went well with the Twilio.Voice.iOS sln.

I now get 7 errors starting with 'Linker command failed with exit code 1'.  Do you know why I couldn't get the NuGet package to work firstly or why the referenced dll is causing issues?  

Also, are there any tutorials anywhere with instructions on pushing calls to Xamarin apps?

**Comment by kier70** [comment]
I've just downloaded and compiled your code after manually placing the .a file in the folder, it all builds the same but referencing the dll gives the same resultant 7 errors.

**Comment by dkornev** [comment]
@kier70 Thank you for your report. I'll try to take a look at this later this week.

**Comment by dkornev** [comment]
@kier70 I've just cloned the repository and build twilio.voice.ios project from scratch. I have no problems with using the csproj file and NuGet both.

Please be sure that you run _bootstrapper.sh_ from _Twilio.Voice.iOS_ folder before you build the project. Also add _--registrar:static_ as additional mtouch arguments on iOS Build dialog for your iOS UI application. I hope it will help.

**Operating System**
Mac OS X 10.14.4
**Visual Studio Community 2019 for Mac**
Version 8.0.3 (build 14)
**Xamarin.iOS**
Version: 12.8.0.0 (Visual Studio Community)
**Mono Framework MDK**
Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

**Comment by kier70** [comment]
Thanks @dkornev I just bottomed out the PC and Mac with fresh OS's and reinstalled everything which seems to have done the trick.  Not sure what the problem was but I can get the project referenced, haven't tried the NuGet package yet but I'm sure that will be the same.

I'll go see if I can find the APN instructions now.

**Comment by dkornev** [comment]
@kier70 I really recommend to use official tutorials:
https://github.com/twilio/voice-quickstart-swift

Closing the issue

**Comment by kier70** [comment]
If using NuGet are there any additional steps to be taken? I'm still getting the same error....

**Comment by dkornev** [comment]
No additional steps required. Let me check it again later

**Comment by kier70** [comment]
okay, thanks.  If there is a ui project available somewhere please let me know and I'll check my setup against it.

**Comment by dkornev** [comment]
Should be fixed now.
https://github.com/dkornev/TwilioVoiceXamarinIOS
