### ISSUE TITLE
Support of Twilio Video Android bindings for Version 4.x

### ISSUE THREAD

**Issue by koystinen** [dkornev/TwilioXamarinBindings#6]
any plans on adding support of new 4.0 released in February?

current latest version of Twilio Video Android is 4.1.1 (April 11th, 2019)

**Comment by dkornev** [comment]
Yes, I have plans to update bindings but I don't do that often. We are still using Video.Android 2.x in our prod apps which works great. So I don't have any dates yet.

But if you want to help development, feel free to join ;-)

**Comment by dkornev** [comment]
I have updated Twilio Video Android binding to 4.3.0 and tested it.
But now it's moved to a separate repository: https://github.com/dkornev/TwilioVideoXamarinAndroid
