### ISSUE TITLE
In <declare-styleable> VideoView, unable to find attribute overlaySurface

### ISSUE THREAD

**Issue by koystinen** [dkornev/TwilioXamarinBindings#7]
Getting build error:

`In <declare-styleable> VideoView, unable to find attribute overlaySurface`

When trying to build Droid sample project, using the referencing V3 Twilio.Video.Android.csproj, with video-android-3.2.2.aar file from the GitHub.
Verified that values.xml file has following line:
`<attr name="overlaySurface" format="boolean"/>`

Not sure what am I missing...

Update:
Okay... managed to have sample project build using v2... so issue is with V3

**Comment by rsuk** [comment]
Anyone have any ideas on this? Fails with both nuget reference and locally built .dll reference. I too have confirmed that the values.xml file contains the overlaySurface entry.

**Comment by dkornev** [comment]
@rsuk I'll try to get it fixed this weekend.
I'm personally still using v2 and it works there

**Comment by mduchev** [comment]
Yep, same issue here.

**Comment by dkornev** [comment]
Fixed.
I have updated Twilio Video Android binding to 4.3.0 and tested it.
But now it's moved to a separate repository: https://github.com/dkornev/TwilioVideoXamarinAndroid
