### ISSUE TITLE
Unable to set TVODefaultAudioDevice to TVOAudioDevice

### ISSUE THREAD

**Issue by HassanNazari** [dkornev/TwilioXamarinBindings#8]
When trying to set TwilioVoice.AudioDevice to the default instance of TVODefaultAudioDevice it throws an error with type mismatch.

From Twilio quickstart ios:

> The important thing to remember when providing a TVOAudioDevice is that the device must be set before performing any other actions with the SDK (such as connecting a Call, or accepting an incoming Call). In this case we've already initialized our own TVODefaultAudioDevice instance which we will now set.

TwilioVoice.audioDevice = audioDevice

**Comment by dkornev** [comment]
Fixed in a separate repository https://github.com/dkornev/TwilioVoiceXamarinIOS
Nuget package is also updated.
Please let me know if it fixes your issue
